import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";

import { Sidebar } from "@/components/Sidebar/Sidebar";
import Header from "@/components/dashboardHeader/Header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex items-start justify-between bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className=" border-r min-h-screen">
          <Sidebar />
        </div>
        <main className="grid h-full w-full pl-[300px]">
          <Header />
          <div className="p-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
